version: "3"

volumes:
      proagildb:
      
networks:
       frontend:

services:

      proagil:
        build:
         context: .
         dockerfile: Dockerfile.multi
         
        networks :         
         - frontend
        
        volumes:
          - proagildb:/app
          
        ports:
         - 5000:80
